<?php 
return array (
  'site_name' => '场景秀',
  'site_url' => '//h5.ideavip.cn',
  'site_url_cdn_static' => '//h5cdn.h5.ideavip.cn',
  'site_url_cdn_uploads' => '//cdn.h5.ideavip.cn',
  'site_title' => 'H5内容引擎 企业版 独立部署版 ',
  'keyword' => 'H5内容引擎,企业版,独立部署版',
  'content' => '易企秀移动场景,免费为中小微企业或团队提供业务场景应用展示、潜在客户在线报名收集、管理和二次营销',
  'web_muban_status' => '3',
  'open_mobile' => '0',
  'is_open_reg' => '1',
  'is_user_anli_shenghe' => '0',
  'reg_validdays' => '5',
  'allow_nums' => '5',
  'xd' => '99',
  'eq_main_bg' => '#f0f0f0',
  'main_info_bg' => '#ffffff',
  'header_tpl_hover_bg' => '#08a1ef',
  'creat_head' => '#08a1ef',
  'create-bg' => '#d0cfd8',
  'lastpagetext' => 'IdeaVip团队',
  'lastpagetext_color' => '#23a3d3',
  'lastpagelink' => '//H5.ideavip.cn',
  'qi_ad_xds' => '99',
  'loadingLogo_qi_xd' => '88',
  'ipc' => '京ICP备88888888号',
  'countCode' => '',
);